server:
  port: 8090
spring:
  thymeleaf:
    mode: HTML5
    cache: false
  application:
    name: rip-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.80.248:23309/rip?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: kjrip2020JHDhDhYEfLrTAKmV
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
# Hibernate ddl auto (create, create-drop, update, validate, none)
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

logging:
  level:
    root: info